# Site settings
title: "Major League Baseball: Wins Created"
email: pat5547@gmail.com
description: "Decomposing wins into wins created per player using expecations"
url: "http://sportmodel.github.io/mlb"
baseurl: ""
github_username:  sportModel

# Build settings
markdown: kramdown
exclude: [new]

# Necessary for GitHub
relative_links:
  enabled:     false

# Defaults
defaults:
  -
    scope:
      type: posts
    values:
      layout: post
      rel: "../../../"
  -
    scope:
      path: ""
    values:
      layout: "default"
      rel: "./"
