year <- as.numeric(commandArgs(TRUE)[[1]])
library(xtable)
mlb.par <- setDefaultPar(year)
mlb.raw <- formatData()
mlb.vc <- calculateVC(mlb.raw)
mlb.team <- calculateTeam(mlb.raw,mlb.vc)
save(mlb.par, mlb.raw, mlb.vc, mlb.team, file=paste("data/",year,"/mlb.rda",sep=""))
updateWebsite(mlb.raw, mlb.vc, mlb.team)

# load('data/2018/mlb.rda')
