# Requires 1 argument: year
# baseball-reference fangraphs internal
./teamget.sh NYY  9 nyy $1
./teamget.sh TOR 14 tor $1
./teamget.sh BOS  3 bos $1
./teamget.sh TBR 12 tam $1
./teamget.sh BAL  2 bal $1
./teamget.sh CHW  4 chw $1
./teamget.sh DET  6 det $1
./teamget.sh MIN  8 min $1
./teamget.sh KCR  7 kan $1
./teamget.sh CLE  5 cle $1
./teamget.sh OAK 10 oak $1
./teamget.sh TEX 13 tex $1
./teamget.sh LAA  1 laa $1
./teamget.sh HOU 21 hou $1
./teamget.sh SEA 11 sea $1
./teamget.sh ATL 16 atl $1
./teamget.sh PHI 26 phi $1
./teamget.sh WSN 24 was $1
./teamget.sh NYM 25 nym $1
./teamget.sh MIA 20 fla $1
./teamget.sh PIT 27 pit $1
./teamget.sh MIL 23 mil $1
./teamget.sh STL 28 stl $1
./teamget.sh CHC 17 chc $1
./teamget.sh CIN 18 cin $1
./teamget.sh SFG 30 sfo $1
./teamget.sh SDP 29 sdg $1
./teamget.sh COL 19 col $1
./teamget.sh LAD 22 lad $1
./teamget.sh ARI 15 ari $1
