# Requires 1 argument: year
./fgget.sh Yankees nyy $1
./fgget.sh Blue\%20Jays tor $1
./fgget.sh Red\%20Sox bos $1
./fgget.sh Devil\%20Rays tam $1
./fgget.sh Orioles bal $1
./fgget.sh White\%20Sox chw $1
./fgget.sh Tigers det $1
./fgget.sh Twins min $1
./fgget.sh Royals kan $1
./fgget.sh Indians cle $1
./fgget.sh Athletics oak $1
./fgget.sh Rangers tex $1
./fgget.sh Angels laa $1
./fgget.sh Mariners sea $1
./fgget.sh Braves atl $1
./fgget.sh Phillies phi $1
./fgget.sh Nationals was $1
./fgget.sh Mets nym $1
./fgget.sh Marlins fla $1
./fgget.sh Pirates pit $1
./fgget.sh Brewers mil $1
./fgget.sh Cardinals stl $1
./fgget.sh Cubs chc $1
./fgget.sh Reds cin $1
./fgget.sh Astros hou $1
./fgget.sh Giants sfo $1
./fgget.sh Padres sdg $1
./fgget.sh Rockies col $1
./fgget.sh Dodgers lad $1
./fgget.sh Diamondbacks ari $1
